services:
    ongr_translations.filter.domain:
        class: ONGR\FilterManagerBundle\Filter\Widget\Choice\MultiTermChoice
        calls:
            - ["setRequestField", ["domains"]]
            - ["setField", ["domain"]]

    ongr_translations.filter.tag:
        class: ONGR\FilterManagerBundle\Filter\Widget\Choice\MultiTermChoice
        calls:
            - ["setRequestField", ["tags"]]
            - ["setField", ["tags"]]

    ongr_translations.filter.size:
        class: ONGR\TranslationsBundle\Filter\SizeFilter
        calls:
            - ["setSize", ["%ongr_translations.list_size%"]]

    ongr_translations.filters_container:
        class: ONGR\FilterManagerBundle\Search\FilterContainer
        calls:
            - ["set", ["domain", "@ongr_translations.filter.domain"]]
            - ["set", ["tag", "@ongr_translations.filter.tag"]]
            - ["set", ["size", "@ongr_translations.filter.size"]]
