ongr_translations_list_page:
    path: /list
    methods: [GET]
    defaults:
        _controller: ongr_translations.controller.list:listAction

ongr_translations_translation_page:
    path: /translation/{domain}/{translation}
    methods: [GET]
    defaults:
        _controller: ongr_translations.controller.list:translationAction

ongr_translations_api_edit:
    path: /_api/edit
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:edit
    options:
        expose: true
            
ongr_translations_api_delete:
    path: /_api/delete
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:delete
    options:
        expose: true

ongr_translations_api_add:
    path: /_api/add
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:add
    options:
        expose: true

ongr_translations_api_get:
    path: /_api/get
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:get
    options:
        expose: true

ongr_translations_api_check:
    path: /_api/check
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:check
    options:
        expose: true

ongr_translations_api_export:
    path: /_api/export
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:export
    options:
        expose: true

ongr_translations_api_history:
    path: /_api/history
    methods: [POST]
    defaults:
        _controller: ONGRTranslationsBundle:Api:history
    options:
        expose: true

ongr_translations_translation_add_tag:
    path: /translation/add/tag
    methods: [POST]
    defaults:
        _controller: ongr_translations.controller.translation:addTagAction
    options:
        expose: true

ongr_translations_translation_messages_edit:
    path: /translation/messages/edit
    methods: [POST]
    defaults:
        _controller: ongr_translations.controller.translation:editAction
    options:
        expose: true
