services:
  ongr_translations.command.export:
    class: ONGR\TranslationsBundle\Command\ExportCommand
    calls:
      - [setContainer, ["@service_container"]]

  ongr_translations.file_import:
    class: ONGR\TranslationsBundle\Translation\Import\FileImport
    arguments:
      - [ "@ongr_translations.loaders_container" ]

  ongr_translations.import:
    class: ONGR\TranslationsBundle\Service\Import
    arguments:
      - "@ongr_translations.file_import"
      - "@ongr_translations.storage"
      - %kernel.root_dir%
      - %kernel.bundles%
      - %ongr_translations.bundles%
    calls:
      - [ setLocales, [ %ongr_translations.managed_locales% ] ]
      - [ setDomains, [ %ongr_translations.domains% ] ]
      - [ setFormats, [ %ongr_translations.formats% ] ]

  ongr_translations.export.yaml:
    class: ONGR\TranslationsBundle\Translation\Export\YmlExport

  ongr_translations.export:
    class: ONGR\TranslationsBundle\Service\Export
    arguments:
      - "@ongr_translations.loaders_container"
      - "@ongr_translations.storage"
      - "@ongr_translations.export.yaml"
    calls:
      - ["setManagedLocales", ["%ongr_translations.managed_locales%"]]

  ongr_translations.loaders_container:
    class: ONGR\TranslationsBundle\Service\LoadersContainer

  ongr_translations.request_handler:
    class: ONGR\TranslationsBundle\Service\RequestHandler
